swagger: "2.0"
info:
  description: "This is API Documentation for Tresor App"
  version: "1.0.0"
  title: "Tresor API"
host: "tresor.website"
schemes:
  - "https"
consumes:
  - application/json
  - application/x-www-form-urlencoded
produces:
  - application/json
tags:
  - name: credential
paths:
  /user:
    post:
      tags: 
        - credential
      summary: Create new user
      parameters:
        - in: body
          name: body
          required: true
          schema:
            $ref: "#/definitions/Credential"
        required: true
        content:
          application/json:
            schema: 
              $ref: '#/components/schemas/Credential'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/Credential'

      responses:
        204:
          description: "user created"
  /session:
    post:
      tags:
        - credential
      summary: "Login user"
definitions:
  Credential:
    type: object
    properties:
      email:
        type: string
      password:
        type: string