swagger: "2.0"
info:
  description: "This is API Documentation for Tresor App"
  version: "1.0.0"
  title: "Tresor API"
host: "tresor.website"
schemes:
  - "https"
consumes:
  - application/json
  - application/x-www-form-urlencoded
produces:
  - application/json
tags:
  - name: credential
paths:
  /users:
    post:
      tags: 
        - credential
      summary: Create new user
      parameters:
        - in: body
          name: body
          required: true
          schema:
            $ref: "#/definitions/Credential"
      responses:
        204:
          description: "user created"
  /sessions:
    post:
      tags:
        - credential
      summary: Login user
      parameters:
        - in: body
          name: body
          required: true
          schema:
            $ref: "#/definitions/Credential"
      responses:
        200:
          description: Successfully get token
          schema:
            $ref: "#/definitions/Token"
        401:
          description: email/password wrong
          schema:
            type: object
            properties:
              message:
                type: string
  /spendings/:
    get:
      tags:
        - spendings
      summary: get list spendings  
      operationId: getSpendingList
      parameters:
        - name: dateStart
          description: start date filter
          in: query
          type: string
        - name: dateEnd
          description: end date filter
          in: query
          type: string
        - name: page
          description: page filter
          in: query
          type: integer
        - name: tags
          description: tags filter
          in: query
          type: array
          items:
            type: string
      responses:
        200:
          description: Sucessfully get spendings
          schema:
            type: object
            properties:
              count: 
                type: int
              data:
                type: array
                items:
                  $ref: "#/definitions/Spending"
definitions:
  Credential:
    type: object
    properties:
      email:
        type: string
      password:
        type: string
  Token:
    type: object
    properties:
      token:
        type: string
  Spending:
    type: object
    properties:
      id:
        type: integer
      amount:
        type: double
      tags:
        type: array
        items: 
          type: string
      date:
        type: date
      info:
        type: string
      category:
        type: string
      